# Generated by Django 4.0.6 on 2023-01-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_portfolio_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='service_type',
            field=models.CharField(choices=[('Tech solutions', 'Tech solutions'), ('Web development', 'Web development'), ('Data Analysis', 'Data Analysis'), ('SEO', 'SEO'), ('Graphic Designing', 'Graphic Designing'), ('Marketing', 'Marketing')], max_length=100),
        ),
    ]
